package edu.curtin.oose2024s1.assignment2.controller.messagehandler;

import edu.curtin.oose2024s1.assignment2.exceptions.MessageHandlingException;
import edu.curtin.oose2024s1.assignment2.model.*;

/**
 * Handles Delivery messages generated by BikeShopInput
 */
public class DeliveryMessageHandler implements MessageHandler
{
    @Override
    public void handleMessage(BikeShopInfo info, String message) throws MessageHandlingException
    {
        if(info.hasSpace(10) && info.getMoney() >= 10000)
        {
            info.addBikes(10);
            info.addMoney(-5000);
            info.notifyStateChange("10 bikes delivered.");
        }
        else if(info.getMoney() <= 10000)
        {
            throw new MessageHandlingException("Not enough cash (for the shop to purchase new bikes)");
        }
        else
        {
            throw new MessageHandlingException("Not enough space (to store more bikes)");
        }
    }
}