package edu.curtin.oose2024s1.assignment2.controller.messagehandler;

import edu.curtin.oose2024s1.assignment2.exceptions.MessageHandlingException;
import edu.curtin.oose2024s1.assignment2.model.*;

/**
 * Handles Drop Off messages generated by BikeShopInput
 */
public class DropOffMessageHandler implements MessageHandler
{
    @Override
    public void handleMessage(BikeShopInfo info, String message) throws MessageHandlingException
    {
        if(info.hasSpace(1))
        {
            String email = message.split(" ")[1];
            Bike bike = new Bike();
            bike.setEmail(email);
            bike.setState(new ServicingState());
            info.getBikes().add(bike);
            info.notifyStateChange("Bike dropped off for servicing.");
        }
        else
        {
            throw new MessageHandlingException("Not enough space (to store more bikes)");
        }
    }
}