package edu.curtin.oose2024s1.assignment2.controller.messagehandler;

import edu.curtin.oose2024s1.assignment2.exceptions.MessageHandlingException;
import edu.curtin.oose2024s1.assignment2.model.*;

/**
 * Handles Pick Up messages generated by BikeShopInput
 */
public class PickUpMessageHandler implements MessageHandler
{
    @Override
    public void handleMessage(BikeShopInfo info, String message) throws MessageHandlingException
    {
        String email = message.split(" ")[1];
        Bike bike = info.getBikeByEmail(email);
        if(bike != null && bike.getState() instanceof PickUpState)
        {
            if(!bike.getHasTakenPayment())
            {
                info.addMoney(100);
                bike.setHasTakenPayment(true);
            }
            
            info.removeBike(bike);
            info.notifyStateChange("Bike picked up.");
        }
        else if(bike != null && bike.getState() instanceof ServicingState)
        {
            throw new MessageHandlingException("Bike not ready (still being serviced).");
        }
        else
        {
            throw new MessageHandlingException("No bike matching customer email (for pick-up): " + email);
        }
    }
}