package edu.curtin.oose2024s1.assignment2.controller.messagehandler;

import edu.curtin.oose2024s1.assignment2.exceptions.MessageHandlingException;
import edu.curtin.oose2024s1.assignment2.model.*;

/**
 * Handles Purchase Online messages generated by BikeShopInput
 */
public class PurchaseOnlineMessageHandler implements MessageHandler
{
    @Override
    public void handleMessage(BikeShopInfo info, String message) throws MessageHandlingException
    {
        Bike bike = info.getAvailableBike();
        if(bike != null)
        {
            String email = message.split(" ")[1];
            bike.setEmail(email);
            bike.setState(new PickUpState());
            bike.setHasTakenPayment(true);
            info.notifyStateChange("Bike purchased online.");
            info.addMoney(1000);
        }
        else
        {
            throw new MessageHandlingException("No bikes left (for a customer to purchase)");
        }
    }
}